#! /bin/bash

if [[ $1 = "remove" ]]; then
    cd ~/software/8812au-20210629
    sudo ./remove-driver.sh
    rm -rf ~/software/8812au-20210629
    echo "Done. Reboot recommended"
    exit 0
fi

sudo pacman -Syu
sudo pacman -S --noconfirm linux-headers dkms git bc iw
git clone https://github.com/morrownr/8812au-20210629.git ~/software/8812au-20210629
cd ~/software/8812au-20210629
sudo ./install-driver.sh
echo "Done. Reboot recommended"
