#! /bin/bash

if [[ $1 = "remove" ]]; then
    yay -R magicq
    echo "Done."
    exit 0
fi

sudo pacman -U https://archive.archlinux.org/packages/q/qt5-webkit/qt5-webkit-5.212.0alpha4-18-x86_64.pkg.tar.zst
yay -S magicq

echo "Done."
